name: NPM Cache and Install dependencies
description: NPM Cache and Install dependencies
author: "mdasifnasin"

inputs:
  path_of_the_file:
    required: true

runs:
  using: composite
  steps:
    - name: Cache NPM dependencies
      uses: actions/cache@v4.2.0
      with:
        path: ${{ inputs.path_of_the_file }}
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

    - name: Installing Dependencies
      run: |
        npm -v
        node -v
        npm install
      shell: 
branding:
    icon: 'award'
    color: 'green'
